### PR TITLE
Skip Empty Files

### PR DESCRIPTION
**Pull request by daniellmb**
It's silly that the whole analysis process throws an error and dies if any of the files are empty. This change will simply skip them.

### CODE REVIEW

**Comment by alexeyraspopov** [comment]
Thanks, it's really useful addition. But can you use filter instead of if..return? Like

```
files.filter(function(file){
    return file.contents.toString() > 0;
}).forEach(function(file){
    ...
```

**Comment by daniellmb** [comment]
updated, but it is calling toString twice on the file contents buffer now :)

**Comment by alexeyraspopov** [comment]
It couldn't be a bottleneck :)

...I hope

**Comment by alexeyraspopov** [comment]
I will publish patch version later.

Thanks!

**Pull request merged**
